# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'C', b'cz\xc4\x99\xc5\x9bciowy'), (b'K', b'ko\xc5\x84cowy')], max_length=1, verbose_name=b'Typ')),
                ('slug', models.SlugField(verbose_name=b'Odnosnik')),
                ('object', models.CharField(max_length=100, verbose_name=b'Obiekt:')),
                ('contractor', models.CharField(max_length=100, verbose_name=b'Wykonany przez:')),
                ('agreement', models.CharField(max_length=100, verbose_name=b'Na podstawie wyceny:')),
                ('order', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Na podstawie wyceny:')),
                ('agreement_day', models.CharField(max_length=100, verbose_name=b'z dnia')),
                ('inv1', models.CharField(max_length=50, verbose_name=b'Komisja inwestor 1:')),
                ('inv2', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Komisja inwestor 2:')),
                ('inv3', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Komisja inwestor 3:')),
                ('cont1', models.CharField(max_length=50, verbose_name=b'Komisja wykonawca 1:')),
                ('cont2', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Komisja wykonawca 2:')),
                ('date', models.DateField(verbose_name=b'Data protoko\xc5\x82u')),
                ('works', models.TextField(verbose_name=b'W dniu ... komisja dokona\xc5\x82a odbioru ni\xc5\xbcej wymienionych rob\xc3\xb3t:')),
                ('works_quality', models.CharField(max_length=100, verbose_name=b'Roboty zosta\xc5\x82y wykonane:')),
                ('mistakes', models.TextField(verbose_name=b'Usterki:')),
                ('correct_mistakes_day', models.CharField(max_length=20, verbose_name=b'Komisja zobowi\xc4\x85zuje wykonawc\xc4\x99 do usuni\xc4\x99cia usterek w terminie do dnia:')),
                ('resolutions', models.TextField(verbose_name=b'Komisja postanawia:')),
            ],
            options={
                'verbose_name': 'Protok\xf3\u0142 odbioru rob\xf3t',
                'verbose_name_plural': 'Protoko\u0142y odbioru rob\xf3t',
            },
        ),
    ]
